use bd_Sistema;

        insert into Menu(idMenu,Nome) values( "101","Cadatro->Usuario");
        insert into Menu(idMenu,Nome) values( "102","Cadatro->Grupo Usuario");
        insert into Menu(idMenu,Nome) values( "103","Cadatro->Cliente");
        insert into Menu(idMenu,Nome) values( "104","Cadatro->Cidade");
        insert into Menu(idMenu,Nome) values( "105","Cadatro->Bairro");
        insert into Menu(idMenu,Nome) values( "106","Cadatro->Profissao");
        insert into Menu(idMenu,Nome) values( "107","Cadatro->Fornecedor");
        insert into Menu(idMenu,Nome) values( "108","Cadatro->Profissional");
        insert into Menu(idMenu,Nome) values( "109","Cadatro->Grupo Profissional");
        insert into Menu(idMenu,Nome) values( "110","Cadatro->Produto");
        insert into Menu(idMenu,Nome) values( "111","Cadatro->Tipo Material");
        insert into Menu(idMenu,Nome) values( "112","Cadatro->Unidade");
        insert into Menu(idMenu,Nome) values( "113","Cadatro->Servico");
        insert into Menu(idMenu,Nome) values( "114","Cadatro->Mao Obra");
        insert into Menu(idMenu,Nome) values( "115","Cadatro->Cond. Pagto");
        insert into Menu(idMenu,Nome) values( "116","Cadatro->Comanda");
        insert into Menu(idMenu,Nome) values( "117","Cadastro->Motivos");
        insert into Menu(idMenu,Nome) values( "118","Cadastro->Ramo Produto");
        insert into Menu(idMenu,Nome) values( "201","Movimento->Associar Comanda");
        insert into Menu(idMenu,Nome) values( "202","Movimento->Ordem Servico");
        insert into Menu(idMenu,Nome) values( "203","Movimento->Requisicao");
        insert into Menu(idMenu,Nome) values( "204","Movimento->Pedido");
        insert into Menu(idMenu,Nome) values( "205","Movimento->Comissao Servicos");
        insert into Menu(idMenu,Nome) values( "206","Movimento->Comissao Vendas");
        insert into Menu(idMenu,Nome) values( "207","Movimento->Entrada Notas");
        insert into Menu(idMenu,Nome) values( "208","Movimento->Fechar Arquivo OS");
        insert into Menu(idMenu,Nome) values( "209","Movimento->Fechar Arquivo PED");
        insert into Menu(idMenu,Nome) values( "210","Movimento->Reabrir OS");
        insert into Menu(idMenu,Nome) values( "211","Movimento->Reabrir PED");
        insert into Menu(idMenu,Nome) values( "212","Movimento->Inventario Estoque");
        insert into Menu(idMenu,Nome) values( "213","Movimento->Baixa Boleto OS");
        insert into Menu(idMenu,Nome) values( "214","Movimento->Baixa Boleto PED");
        insert into Menu(idMenu,Nome) values( "215","Movimento->Fechamento Mensal");
        insert into Menu(idMenu,Nome) values( "216","Movimento->Agenda");
        insert into Menu(idMenu,Nome) values( "217","Movimento->Fechar Caixa");
        insert into Menu(idMenu,Nome) values( "301","Consulta->Situacao OS");
        insert into Menu(idMenu,Nome) values( "302","Consulta->Localizar OS");
        insert into Menu(idMenu,Nome) values( "303","Consulta->Localizar Pedido");
        insert into Menu(idMenu,Nome) values( "304","Consulta->Localizar Req");
        insert into Menu(idMenu,Nome) values( "305","Consulta->Comandas Abertas");
        insert into Menu(idMenu,Nome) values( "306","Consulta->Faturamento Servicos");
        insert into Menu(idMenu,Nome) values( "307","Consulta->Faturamento Vendas");
        insert into Menu(idMenu,Nome) values( "308","Consulta->Faturamento Geral");
        insert into Menu(idMenu,Nome) values( "309","Consulta->Fatura Comissao");
        insert into Menu(idMenu,Nome) values( "310","Consulta->Fatura Vendas");
        insert into Menu(idMenu,Nome) values( "311","Consulta->Resumo Movimento");
        insert into Menu(idMenu,Nome) values( "312","Consulta->Produto Movimento");
        insert into Menu(idMenu,Nome) values( "313","Consulta->Fechamento Caixa");
        insert into Menu(idMenu,Nome) values( "314","Consulta->Comandas Movimento");
        insert into Menu(idMenu,Nome) values( "401","Relatorio->Clientes");
        insert into Menu(idMenu,Nome) values( "402","Relatorio->Estoque Produtos");
        insert into Menu(idMenu,Nome) values( "403","Relatorio->Vendas Produtos");
        insert into Menu(idMenu,Nome) values( "404","Relatorio->Recurso Produtos");
        insert into Menu(idMenu,Nome) values( "405","Relatorio->Requis. Produtos");
        insert into Menu(idMenu,Nome) values( "406","Relatorio->Entrada Produtos");
        insert into Menu(idMenu,Nome) values( "407","Relatorio->Servicos");
        insert into Menu(idMenu,Nome) values( "408","Relatorio->Tributos");
        insert into Menu(idMenu,Nome) values( "409","Relatorio->Arquivos");
        insert into Menu(idMenu,Nome) values( "410","Relatorio->Boletos");
        insert into Menu(idMenu,Nome) values( "411","Relatorio->Mala Direta");
        insert into Menu(idMenu,Nome) values("501","Financeiro");
        
        
